use std::fs;
use std::process::Command;
use clipboard_rs::{Clipboard, ClipboardContext};
use std::env;
use std::io::{BufRead, BufReader};

fn main()
{   
    let mut args = env::args().skip(1); // 跳過第 0 個（執行檔路徑）
    let mut input = String::from("./workspace.txt");
    let mut output = String::from("./workspace.txt");
    let mut switch: i8 = 0;
    while let Some(arg) = args.next() {
        match arg.as_str() {
            "-i" => {
                if let Some(val) = args.next() {
                    input = val;
                    switch = 1;
                }
            }
            "-o" => {
                if let Some(val) = args.next() {
                    output = val;
                    switch = 1;
                }
            }
            "f" => {
                switch = 1;
            }
            _ => {}
        }
    }
    if (switch == 1)
    {
        let mut contents = fs::read_to_string(input).expect("Something went wrong reading the file");
        println!("read in:\n{}", contents);

        let settingsFile = fs::File::open("./settings.csv").expect("Unable to open settings");
        let settingsLoader = BufReader::new(settingsFile);
        let mut settings: Vec<Vec<String>> = Vec::new();
        for line in settingsLoader.lines() // This for() is generated by Gemini
        {
            if let Ok(line_str) = line
            {
                // 將每個欄位獨立轉為 String 避開生命週期問題
                let csv_line: Vec<String> = line_str.split(',').map(String::from).collect();
                settings.push(csv_line);
                println!("{:?}", settings);
            }
        }
        for setting in settings.iter()
        {
            contents = contents.replace(&setting[0], &setting[1]);
        }

        fs::write(&output, &contents).expect("Something went wrong writing the file");

        println!("----------\nReplaced result:\n{}", contents);

        contents = fs::read_to_string(output).expect("Something went wrong reading the file");
        println!("----------\nnewly read in:\n{}", contents);
    }
    else
    {
        println!("Clipboard");
        let clipboard = ClipboardContext::new().unwrap();
        let Clipboardcontent = clipboard.get_text().unwrap_or("".to_string());
        let new_clipboard_content = Clipboardcontent
            .replace("@blackboxusboot", "@[computerName]")
            .replace("@blackbox", "@[computerName]")
            .replace("blackbox", "[userName]");
        clipboard.set_text(new_clipboard_content).unwrap();

        let _ = Command::new("cmd.exe").arg("/c").arg("pause").status();
    }
}