use std::fs;
use std::process::Command;
use clipboard_rs::{Clipboard, ClipboardContext};
use std::env;
use std::io::{BufRead, BufReader};
use std::io;

fn main()
{   
    let mut args = env::args().skip(1);
    let mut input = String::from("./workspace.txt"); let mut output = String::from("./workspace.txt");
    let mut switch: bool = false;
    let mut contents = String::new();

    while let Some(arg) = args.next() {
        match arg.as_str() {
            "-i" => {
                if let Some(val) = args.next() {
                    input = val;
                    switch = true;
                }
            }
            "-o" => {
                if let Some(val) = args.next() {
                    output = val;
                    switch = true;
                }
            }
            "f" => {
                switch = true;
            }
            _ => {}
        }
    }

    if (switch)
    {
        contents = fs::read_to_string(input).expect("Something went wrong reading the file");
        println!("read in:\n{}", contents);
    }
    else
    {
        println!("Clipboard");
        let clipboard = ClipboardContext::new().unwrap();
        contents = clipboard.get_text().unwrap_or("".to_string());
    }

    let settingsFile = fs::File::open("./list.csv").expect("Unable to open settings");
    let settingsLoader = BufReader::new(settingsFile);
    let mut settings: Vec<Vec<String>> = Vec::new();
    for line in settingsLoader.lines() // This for() is generated by Gemini
    {
        if let Ok(line_str) = line
        {
            let csv_line: Vec<String> = line_str.split(',').map(String::from).collect();
            settings.push(csv_line);
        }
    }
    for setting in settings.iter()
    {
        contents = contents.replace(&setting[0], &setting[1]);
    }

    println!("----------\nReplaced result:\n{}", contents);
    if switch
    {
        fs::write(&output, &contents).expect("Something went wrong writing the file");
        contents = fs::read_to_string(output).expect("Something went wrong reading the file");
        println!("----------\nnewly read in:\n{}", contents);
    }
    else
    {
        let clipboard = ClipboardContext::new().unwrap();
        clipboard.set_text(contents).unwrap();
        println!("Copied to clipboard!");
    }

    println!("----------------\nPress Enter to exit");
    let mut buffer = String::new(); let _ = io::stdin().read_line(&mut buffer);
}